/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package laundryapp;

import javax.swing.ButtonModel;

/**
 *
 * @author Jed_Knight
 */
public class laundryform extends javax.swing.JFrame {
    

    /**
     * Creates new form laundryform
     */
    public laundryform() {
        initComponents();
        
        reset();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        basketRadio = new javax.swing.JRadioButton();
        blanketRadio = new javax.swing.JRadioButton();
        clothRadio = new javax.swing.JRadioButton();
        dryRadio = new javax.swing.JRadioButton();
        basketCombo = new javax.swing.JComboBox<>();
        blanketCombo = new javax.swing.JComboBox<>();
        clothCombo = new javax.swing.JComboBox<>();
        dryCombo = new javax.swing.JComboBox<>();
        gownRadio = new javax.swing.JRadioButton();
        gownCombo = new javax.swing.JComboBox<>();
        basketHeavy = new javax.swing.JCheckBox();
        basketDelicate = new javax.swing.JCheckBox();
        basketSoak = new javax.swing.JCheckBox();
        blanketHeavy = new javax.swing.JCheckBox();
        blanketDelicate = new javax.swing.JCheckBox();
        blanketSoak = new javax.swing.JCheckBox();
        clothHeavy = new javax.swing.JCheckBox();
        clothDelicate = new javax.swing.JCheckBox();
        clothSoak = new javax.swing.JCheckBox();
        dryHeavy = new javax.swing.JCheckBox();
        dryDelicate = new javax.swing.JCheckBox();
        drySoak = new javax.swing.JCheckBox();
        gownHeavy = new javax.swing.JCheckBox();
        gownDelicate = new javax.swing.JCheckBox();
        gownSoak = new javax.swing.JCheckBox();
        total = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        submit = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("SERVICES:");

        basketRadio.setText("BASKET");
        basketRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                basketRadioActionPerformed(evt);
            }
        });

        blanketRadio.setText("BLANKET");
        blanketRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blanketRadioActionPerformed(evt);
            }
        });

        clothRadio.setText("CLOTH");
        clothRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clothRadioActionPerformed(evt);
            }
        });

        dryRadio.setText("DRY CLEANING");
        dryRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dryRadioActionPerformed(evt);
            }
        });

        basketCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "(none)", "SMALL", "MEDIUM", "BIG BASKET", "OVERFLOWING" }));
        basketCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                basketComboActionPerformed(evt);
            }
        });

        blanketCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "(none)", "SINGLE", "DOUBLE", "QUEEN SIZE", "EXTRA LARGE" }));
        blanketCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blanketComboActionPerformed(evt);
            }
        });

        clothCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "(none)", "SMALL", "BIG", "LARGE", "CURTAIN" }));
        clothCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clothComboActionPerformed(evt);
            }
        });

        dryCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "(none)", "SUIT", "COAT", "JACKET", "TROUSER", "SHIRT", "OVERCOAT", "LEATHER JACKET" }));
        dryCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dryComboActionPerformed(evt);
            }
        });

        gownRadio.setText("GOWNS");
        gownRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gownRadioActionPerformed(evt);
            }
        });

        gownCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "(none)", "WEDDING", "GRADUATION" }));
        gownCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gownComboActionPerformed(evt);
            }
        });

        buttonGroup1.add(basketHeavy);
        basketHeavy.setText("HEAVY");
        basketHeavy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                basketHeavyActionPerformed(evt);
            }
        });

        buttonGroup1.add(basketDelicate);
        basketDelicate.setText("DELICATE");
        basketDelicate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                basketDelicateActionPerformed(evt);
            }
        });

        buttonGroup1.add(basketSoak);
        basketSoak.setText("SOAK");

        buttonGroup2.add(blanketHeavy);
        blanketHeavy.setText("HEAVY");

        buttonGroup2.add(blanketDelicate);
        blanketDelicate.setText("DELICATE");

        buttonGroup2.add(blanketSoak);
        blanketSoak.setText("SOAK");

        buttonGroup3.add(clothHeavy);
        clothHeavy.setText("HEAVY");

        buttonGroup3.add(clothDelicate);
        clothDelicate.setText("DELICATE");
        clothDelicate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clothDelicateActionPerformed(evt);
            }
        });

        buttonGroup3.add(clothSoak);
        clothSoak.setText("SOAK");

        buttonGroup4.add(dryHeavy);
        dryHeavy.setText("HEAVY");

        buttonGroup4.add(dryDelicate);
        dryDelicate.setText("DELICATE");

        buttonGroup4.add(drySoak);
        drySoak.setText("SOAK");

        buttonGroup5.add(gownHeavy);
        gownHeavy.setText("HEAVY");

        buttonGroup5.add(gownDelicate);
        gownDelicate.setText("DELICATE");

        buttonGroup5.add(gownSoak);
        gownSoak.setText("SOAK");

        total.setText("TOTAL");
        total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalActionPerformed(evt);
            }
        });

        reset.setText("RESET");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        submit.setText("SUBMIT");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        cancel.setText("CANCEL");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("PROPERTY OF RIGEL TECHNOLOGIES ©");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("EXTRAS:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(basketRadio)
                                    .addComponent(blanketRadio)
                                    .addComponent(clothRadio)
                                    .addComponent(dryRadio)
                                    .addComponent(gownRadio))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(dryCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(basketCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(blanketCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(clothCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(gownCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(blanketHeavy)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(blanketDelicate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(blanketSoak))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(clothHeavy)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(clothDelicate))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(dryHeavy)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(dryDelicate)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(drySoak)
                                    .addComponent(clothSoak)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(gownHeavy)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(gownDelicate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(gownSoak))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(basketHeavy, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(basketDelicate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(basketSoak))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(submit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(reset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(total, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(82, 82, 82)
                                .addComponent(jLabel2)
                                .addGap(0, 23, Short.MAX_VALUE)))))
                .addGap(284, 284, 284))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(basketRadio)
                    .addComponent(basketCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(basketHeavy)
                    .addComponent(basketDelicate)
                    .addComponent(basketSoak))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(blanketRadio)
                    .addComponent(blanketCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(blanketHeavy)
                        .addComponent(blanketDelicate)
                        .addComponent(blanketSoak)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(clothRadio)
                    .addComponent(clothCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(clothHeavy)
                        .addComponent(clothDelicate)
                        .addComponent(clothSoak)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dryRadio)
                    .addComponent(dryCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(dryHeavy)
                        .addComponent(dryDelicate)
                        .addComponent(drySoak)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gownRadio)
                    .addComponent(gownCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(gownHeavy)
                        .addComponent(gownDelicate)
                        .addComponent(gownSoak)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(total)
                        .addGap(18, 18, 18)
                        .addComponent(reset)
                        .addGap(18, 18, 18)
                        .addComponent(submit)
                        .addGap(18, 18, 18)
                        .addComponent(cancel))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void basketDelicateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_basketDelicateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_basketDelicateActionPerformed

    private void clothDelicateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clothDelicateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clothDelicateActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
     this.dispose();
    }//GEN-LAST:event_cancelActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        
        reset();
        


    }//GEN-LAST:event_resetActionPerformed

    private void basketRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_basketRadioActionPerformed
        if (basketRadio.isSelected()){
            basketCombo.setEnabled(true);
        } 
            
    }//GEN-LAST:event_basketRadioActionPerformed

    private void basketComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_basketComboActionPerformed
basketCombo.setEnabled(false);
        
    }//GEN-LAST:event_basketComboActionPerformed

    private void blanketComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blanketComboActionPerformed
        blanketCombo.setEnabled(false);
    }//GEN-LAST:event_blanketComboActionPerformed

    private void clothComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clothComboActionPerformed
        clothCombo.setEnabled(false);
    }//GEN-LAST:event_clothComboActionPerformed

    private void dryComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dryComboActionPerformed
        dryCombo.setEnabled(false);
    }//GEN-LAST:event_dryComboActionPerformed

    private void gownComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gownComboActionPerformed
        gownCombo.setEnabled(false);
    }//GEN-LAST:event_gownComboActionPerformed

    private void blanketRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blanketRadioActionPerformed
        if (blanketRadio.isSelected()){
            blanketCombo.setEnabled(true);
        } 
    }//GEN-LAST:event_blanketRadioActionPerformed

    private void clothRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clothRadioActionPerformed
        if (clothRadio.isSelected()){
            clothCombo.setEnabled(true);
        } 
    }//GEN-LAST:event_clothRadioActionPerformed

    private void dryRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dryRadioActionPerformed
        if (dryRadio.isSelected()){
            dryCombo.setEnabled(true);
        } 
    }//GEN-LAST:event_dryRadioActionPerformed

    private void gownRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gownRadioActionPerformed
        if (gownRadio.isSelected()){
            gownCombo.setEnabled(true);
        } 
    }//GEN-LAST:event_gownRadioActionPerformed

    private void totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalActionPerformed
        
        results();
    }//GEN-LAST:event_totalActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
         
        results();
    }//GEN-LAST:event_submitActionPerformed

    private void basketHeavyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_basketHeavyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_basketHeavyActionPerformed

    /**
     * @param args the command line arguments
     */
    private void results(){
        double price=0;
        double vat=0.15;
        double vatPrice=0;
        
        String basket=basketCombo.getSelectedItem().toString();
        if(basket.matches("SMALL")){
            price=price+50;}
         if(basket.matches("MEDIUM")){
            price=price+100;}
          if (basket.matches("BIG BASKET")){
            price=price+120;}
           if (basket.matches("OVERFLOWING")){
            price=price+150;
        }
        
        String blanket=blanketCombo.getSelectedItem().toString();
        if (blanket.matches("SINGLE")){
            price=price+100;}
         if (blanket.matches("DOUBLE")){
            price=price+120;}
          if (blanket.matches("QUEEN SIZE")){
            price=price+170;}
           if (blanket.matches("EXTRA LARGE")){
            price=price+200;
        }
         
        String cloth=clothCombo.getSelectedItem().toString();
        if (cloth.matches("SMALL")){
            price=price+20;}
         if (cloth.matches("BIG")){
            price=price+25;}
          if (cloth.matches("LARGE")){
            price=price+40;}
           if (cloth.matches("CURTAIN")){
            price=price+70;
            
        }
        
        String dry=dryCombo.getSelectedItem().toString();
        if (dry.matches("SUIT")){
            price=price+100;}
         if (dry.matches("COAT")){
             price=price+60;}
          if (dry.matches("JACKET")){
            price=price+60;}
           if (dry.matches("TROUSER")){
            price=price+40;}
            if (dry.matches("SHIRT")){
            price=price+35;}
             if (dry.matches("OVERCOAT")){
            price=price+110;}
              if (dry.matches("LEATHER JACKET")){
            price=price+250;}
    
        
        
        String gown= gownCombo.getSelectedItem().toString();
        if (gown.matches("WEDDING")){
            price=price+250;}
         if (gown.matches("GRADUATION")){
            price=price+200;}
        
        String extra=null;
        if (basketHeavy.isSelected()){
            price=price+50;
            extra=basketHeavy.getText();
        }
        if (basketDelicate.isSelected()){
            price=price+40;
            extra=basketDelicate.getText();
        }
        if (basketSoak.isSelected()){
            price=price+20;
            extra=basketSoak.getText();
        }
        
        String extra1="(no extra)";
        if (blanketHeavy.isSelected()){
            price=price+50;
            extra1=blanketHeavy.getText();
        }
        if (blanketDelicate.isSelected()){
            price=price+40;
            extra1=blanketDelicate.getText();
        }
        if (blanketSoak.isSelected()){
            price=price+20;
            extra1=blanketSoak.getText();
        }
         String extra2="(no extra)";
        if (clothHeavy.isSelected()){
            price=price+50;
            extra2=clothHeavy.getText();
        }
        if (clothDelicate.isSelected()){
            price=price+40;
            extra2=clothDelicate.getText();
        }
        if (clothSoak.isSelected()){
            price=price+20;
            extra2=clothSoak.getText();
        }
         String extra3="(no extra)";
        if (dryHeavy.isSelected()){
            price=price+50;
            extra3=dryHeavy.getText();
        }
        if (dryDelicate.isSelected()){
            price=price+40;
            extra3=dryDelicate.getText();
        }
        if (drySoak.isSelected()){
            price=price+20;
            extra3=drySoak.getText();
        }
        String extra4="(no extra)";
        if (gownHeavy.isSelected()){
            price=price+50;
            extra4=gownHeavy.getText();
        }
        if (gownDelicate.isSelected()){
            price=price+40;
            extra4=gownDelicate.getText();
        }
        if (gownSoak.isSelected()){
            price=price+20;
            extra4=gownSoak.getText();
        }
         
        
        double priceVat= price+(price*vat);
        vatPrice=priceVat-price;
        
        jTextArea2.append("BASKET:"+"\t\t"+basket+" "+"("+extra+")"+"\nBLANKET:"+"\t\t"+blanket+" "+"("+extra1+")"+"\nCLOTH:"+"\t\t"+cloth
                            +" "+"("+extra2+")"+"\nDRY CLEANING:"+"\t"+dry+" "+"("+extra3+")"+"\nGOWN:"+"\t\t"+gown+" "+"("+extra4+")"+
                            "\n------------------------------------------------------------------"
                            +"\nPRICE (vat excl.): "+"\tR"+price+"\nVAT: "+"\t\tR"+vatPrice
                           +"\n-----------------------------------------------------------------"
                            +"\nTOTAL DUE: "+"\t\tR"+priceVat
                            );
        
    }
    
    private void reset(){
         basketRadio.setSelected(false);
        blanketRadio.setSelected(false);
        clothRadio.setSelected(false);
        dryRadio.setSelected(false);
        gownRadio.setSelected(false);
        basketCombo.setSelectedItem("(none)");
        blanketCombo.setSelectedItem("(none)");
        clothCombo.setSelectedItem("(none)");
        dryCombo.setSelectedItem("(none)");
        gownCombo.setSelectedItem("(none)");
        buttonGroup1.clearSelection();
        buttonGroup2.clearSelection();
        buttonGroup3.clearSelection();
        buttonGroup4.clearSelection();
        buttonGroup5.clearSelection();
        jTextArea2.setText(null);
            
        }
    public static void main(String args[]) {
        
        double price=0;
        double vat=0.15;
        
       
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(laundryform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(laundryform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(laundryform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(laundryform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new laundryform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> basketCombo;
    private javax.swing.JCheckBox basketDelicate;
    private javax.swing.JCheckBox basketHeavy;
    private javax.swing.JRadioButton basketRadio;
    private javax.swing.JCheckBox basketSoak;
    private javax.swing.JComboBox<String> blanketCombo;
    private javax.swing.JCheckBox blanketDelicate;
    private javax.swing.JCheckBox blanketHeavy;
    private javax.swing.JRadioButton blanketRadio;
    private javax.swing.JCheckBox blanketSoak;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JButton cancel;
    private javax.swing.JComboBox<String> clothCombo;
    private javax.swing.JCheckBox clothDelicate;
    private javax.swing.JCheckBox clothHeavy;
    private javax.swing.JRadioButton clothRadio;
    private javax.swing.JCheckBox clothSoak;
    private javax.swing.JComboBox<String> dryCombo;
    private javax.swing.JCheckBox dryDelicate;
    private javax.swing.JCheckBox dryHeavy;
    private javax.swing.JRadioButton dryRadio;
    private javax.swing.JCheckBox drySoak;
    private javax.swing.JComboBox<String> gownCombo;
    private javax.swing.JCheckBox gownDelicate;
    private javax.swing.JCheckBox gownHeavy;
    private javax.swing.JRadioButton gownRadio;
    private javax.swing.JCheckBox gownSoak;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JButton reset;
    private javax.swing.JButton submit;
    private javax.swing.JButton total;
    // End of variables declaration//GEN-END:variables
}
